pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS=credentials('dockerhub')
    }
 
    stages {
        stage('Initialize Stage') {
            steps {
            
                echo 'Initial : Delete  containers and images'
                 dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Current path is ${pwd()}"
                    sh "docker-compose down --rmi all --volumes || true"
                }
            }
        }


        stage('Build Stage') {
            steps {
                dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Current path is ${pwd()}"
                    sh "docker-compose build"
                }
            }
        }
        stage('Login Stage') {
          steps {
            echo "Login : Logging in . .."
           
            sh 'echo $dockerhub_CREDENTIALS_PSW | docker login -u $dockerhub_CREDENTIALS_USR --password-stdin'
          }
        }

        stage('Push Stage') {
            steps {
                dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Push : Current path is ${pwd()}"
                    sh "docker-compose push"
                }
            }
        }
        stage('Trigger Slave dockerhub last up') {
            steps {
                dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Trigger : calling Slave job . . ."
                    sh 'echo "HELLO ${dockerhub_CREDENTIALS_USR}"'
                    build job: 'Slave', parameters: [string(name: 'dockerhub_CREDENTIALS_USR', value: env.dockerhub_CREDENTIALS_USR), string(name: 'dockerhub_CREDENTIALS_PSW', value: env.DOCKERHUB_CREDENTIALS_PSW)]
                }
            }
        }

    
       

    }
}
